apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: port-np-controller
spec:
  resources:
  - apiVersion: v1
    resource: services
    annotationSelector:
      matchExpressions:
      - {key: network-zone, operator: In, values: ['true']}
  attachments:
  - apiVersion: networking.k8s.io/v1
    resource: networkpolicies
  hooks:
    sync:
      webhook:
        url: http://port-np-controller:8080/port-np-controller
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: port-np-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: port-np-controller
    spec:
      containers:
      - name: hooks
        image: docker.io/metacontroller/jsonnetd:0.1
        imagePullPolicy: Always
        workingDir: /hooks
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: port-np-controller
---
apiVersion: v1
kind: Service
metadata:
  name: port-np-controller
spec:
  selector:
    app: port-np-controller
  ports:
  - port: 8080
    targetPort: 8080